version: "3.10"

services:
  webapp:
    container_name: webapp
    build: ./webapp
    restart: always
    ports:
      - "5050:5050"
    expose:
      - 5050


  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    expose:
      - "8080"
    ports:
      - "80:8080"

networks:
  webappnetwork: